
# Compare CR1 and CR2

```{r}
library(yingtools2)
```

## Outcomes of patients in CR1 vs. CR2 - Fig 1h
```{r, warning=F,  message=FALSE}

cohort_outcomes<-cohort %>% mutate(VPFS1m=VPFS-1) 

fit<-survfit(Surv(cohort_outcomes$VPFS, cohort_outcomes$VRelapse)~PriorRelapse, data=cohort_outcomes) # VPFS confirmed by OM to use VPFS

p1 <- ggsurvplot(fit, data=cohort_outcomes,
           palette = c("#2166ac", "#b2182b"),
           conf.int=TRUE,
           pval=TRUE,
           risk.table = T,
           xlim = c(0,36), 
          break.x.by = 6 )

ggsave("../Figures/fig1h_plot.pdf", p1$plot, height=4, width=5)
ggsave("../Figures/fig1h_table.pdf", p1$table, height=2, width=5)

```

## Copmare a-div in 1st and second remossion - fig 1d
```{r, warning=FALSE,  message=FALSE}
baseline_samples_abxfiltered %>% 
  left_join(asv_alpha) %>% 
  left_join(cohort) %>% 
  mutate(PriorRelapse=as.character(PriorRelapse)) %>% 
  ggplot(aes(x=PriorRelapse, y=simpson_reciprocal, color=PriorRelapse))+
  geom_boxplot(width=0.4)+
  geom_jitter(width=0.4, alpha=0.6)+
  stat_compare_means(comparisons=list(c("1", "2")),
                     method="wilcox.test",
                     correct=FALSE)+
  scale_color_manual(values=c("#2166ac","#b2182b"))+
  theme_classic()+
  theme(legend.position = "none")+
  labs(y="alpha diversity")

ggsave("../Figures/fig1d.pdf", width=3, height=3.5, dpi=150)

```


## Create a PCoA - Fig 1e
```{r, warning=F,  message=FALSE}
physeq2 <- readRDS("../Data/03_phyloseq2_16s_aft_rev2.rds")

phyloseq3<- phy.collapse.bins(physeq2, level=4,
                            criteria = max.pctseqs <= 0.01 | pct.detectable <= 0.1)
ord <- phyloseq::ordinate(phyloseq3%>% tax_glom("genus"), method = "PCoA", distance = "bray")

plot_ordination(phyloseq3%>% tax_glom("genus"),ord, color = "PriorRelapse") +
  ggplot2::stat_ellipse(
    mapping = aes(group = PriorRelapse, color = PriorRelapse), 
    level = 0.95,
    linewidth = 1
  ) + scale_color_manual(values=c("#2166ac","#b2182b"))+theme_classic()+theme(legend.position = "none")
ggsave("../Figures/fig1e.pdf", width=6.5, height=4.5, dpi=150)

pcoa_df <- ord$vectors %>%
  data.frame() %>%
  dplyr::select(Axis.1, Axis.2) %>%
  rownames_to_column("sampleid") %>%
  left_join(
    data.frame(sample_data(phyloseq3))%>%
  rownames_to_column("sampleid") ,
    by = "sampleid"
  )


```



## PCoA with a-diversity - Fig 1f
```{r, warning=F,  message=FALSE}
pcoa_df <- pcoa_df %>% left_join(asv_alpha, by="sampleid")
pcoa_df %>%
  ggplot(aes(x = Axis.1, y = Axis.2, color=log10(simpson_reciprocal), shape=PriorRelapse)) +
  geom_point(alpha = 0.7, size = 3) +
  xlab("PCoA1")+
  ylab("PCoA2")+
 scale_color_gradientn(colors = c("#0c2c84", "#fee391", "#de2d26")) +
  theme(
    axis.text.x = element_text(size = 15, face="bold", angle= 0, vjust = 0.5),
    axis.text.y = element_text(size = 15, face="bold")
  )+
  theme_classic()

ggsave("../Figures/fig1f.pdf", width=7, height=4.5, dpi=150)
```

## PCoA with HCT and age - suppl fig 1f
```{r, warning=F,  message=FALSE}

pcoa_df %>%
  mutate(age_y = age_vaccine/12,
         age_bin = ifelse(age_y>=5, "older","younger"),
         age_bin = factor(age_bin, levels=c("younger","older")))%>%
  ggplot(aes(x = Axis.1, y = Axis.2, color=age_bin, shape=HCT)) +
  geom_point(alpha = 0.7, size = 3) +
  xlab("PCoA1")+
  ylab("PCoA2")+
  scale_color_manual(values = c( "#c51b8a", "#089099")) +
  facet_wrap(~PriorRelapse)+
  theme(
    axis.text.x = element_text(size = 15, face="bold", angle= 0, vjust = 0.5),
    axis.text.y = element_text(size = 15, face="bold")
  )+
  theme_classic()

ggsave("../Figures/suppl_fig1f.pdf", width=8, height=4.5, dpi=150)

```







