---
title: "05-TopicModels"
output: html_document
date: "2026-10-06"
---

```{r warning=FALSE, message=FALSE}

library(DirichletMultinomial)
library(topicmodels)
library(tidytext)
library(vdbR)
library(survival)
library(survminer)
```

This rmd will generate Fig2 including Suppl Fig 2 and Suppl Table 4 and Supple Table 5

# fig2a: titers and alpha diversity
```{r}
baseline_samples_abxfiltered <- read.csv("../Data/03_baseline_samples_abxfiltered.csv")
baseline_samples_abxfiltered %>% 
  left_join(asv_alpha) %>% 
  left_join(cohort) %>% 
  left_join(glucan, by ="UPN") %>%
  inner_join(titers) %>%
  ggplot(aes(x=simpson_reciprocal, y=c4_titer))+
  geom_point(size=2)+
  geom_smooth(method=lm)+
  stat_cor(method = "spearman")+
  theme_classic() +
  facet_grid(.~PriorRelapse)+ #to evaluate separate in CR1 and CR2 patients
  labs(x="α-diversity",
       y="Anti-GD2 (μg/ml)")+
  theme(axis.text = element_text(size=10)
  )
ggsave("../Figures/fig2a.pdf", width=4, height=2.5)

```


# topic model separately on CR1 and CR2
Figures/CR1_6topic_model_plot.pdf is Fig2b
Figures/CR2_6topic_model_plot.pdf is Suppl Fig1a

and also Suppl Table 4

```{r}
meta_phyloseq3 <- data.frame(sample_data(phyloseq3)) %>% rownames_to_column("sampleid")

for (i in c("1","2")){
  pull_id <- meta_phyloseq3 %>% filter(PriorRelapse==i) %>% pull(sampleid)
  temp <- readRDS(paste0("../Data/09-CR",i,"lda_model.rds"))
  df_lda_topics <- tidy(temp, matrix = "beta")
  df_lda_docs <- tidy(temp, matrix = "gamma")
  ap_top_terms <- df_lda_topics %>%
    group_by(topic) %>%
    slice_max(beta, n = 10) %>% 
    ungroup() %>%
    arrange(topic, -beta)
  # get the palette color same as what we used for composition plot
  test_palette <- make_microviz_palette(phyloseq3, 41, "genus") %>% data.frame()%>% rownames_to_column("taxa") %>%
    set_names(c("taxa","color"))
  topic_palette <- ap_top_terms %>% group_by(topic) %>%
    slice_max(beta, n = 1)  %>% left_join(test_palette, by=c("term"="taxa")) %>%
    mutate(color=ifelse(term=="g__Faecalibacterium","#17e0a5", color ) )
  color_vector <- setNames(topic_palette$color, topic_palette$topic)
  ap_top_terms %>%
    mutate(term_g = gsub("g__","", term)) %>%
    mutate(term_g = reorder_within(term_g, beta, topic)) %>%
    ggplot(aes(beta, term_g, fill = factor(topic))) +
    geom_col(show.legend = FALSE) +
    facet_wrap(~ topic, scales = "free_y") +
    scale_y_reordered() +
    scale_fill_manual(values=color_vector,
                      name="Microbial\nsignature")+
    theme(axis.text = element_text(size = 6))+
    theme_classic()
  ggsave(paste0("../Figures/CR",i,"_6topic_model_plot.pdf"), height=6, width=10) 
  
  df_sample_weights <- df_lda_docs %>% 
    pivot_wider(id_cols=document,
                names_from = topic,
                values_from = gamma) %>% 
    dplyr::rename(sampleid= document)
  colnames(df_sample_weights)[2:7] = paste0("W",1:6)
  
  df_sample_assignment <- df_lda_docs %>% group_by(document) %>% 
    mutate(gamma = ifelse(gamma == max(gamma),1,0)) %>% 
    ungroup() %>% 
    pivot_wider(id_cols=document,
                names_from = topic,
                values_from = gamma) %>% 
    dplyr::rename(sampleid= document)
  colnames(df_sample_assignment)[2:7] = paste0("S",1:6)
  
  df_topic <- df_sample_weights %>% 
    left_join(df_sample_assignment, by="sampleid") %>%
    left_join(baseline_samples_abxfiltered, by="sampleid") %>%
    left_join(cohort, by="UPN") %>% # adding metadata
    left_join(asv_alpha, by=c("sampleid"))
  #write.csv(df_topic, paste0("../Data/09-CR",i, "_df_topic.csv")) 
  df_topic <- read.csv(paste0("../Data/09-CR",i, "_df_topic.csv"))
  df_titer <- df_topic %>% left_join(titers[,c("UPN","c4_titer","c4_high_median" )], by="UPN") %>%filter(!is.na(c4_titer)) %>%
    left_join(glucan[,c("UPN","time_glucan","group" )], by="UPN")%>%
    mutate(age_y = age_vaccine/12,
           sex= as.character(sex))%>%
  mutate(
    MYCN=factor(MYCN, levels=c("no","amplified")),
    HCT=factor(HCT, levels=c("no","yes")),
    PriorRelapse = factor(PriorRelapse, levels=c("1","2")),
    c4_high_median=factor(c4_high_median, levels = c("low_c4","high_c4")),
    VRelapse = as.numeric(VRelapse),
    age_binary = ifelse(age_y >=5,"older", "younger"),
    group= factor(group,levels = c("group1","group2")),
    sex = factor(sex, levels=c("0","1"))
  )  %>% filter(CR==2)
  uni_v_titer <- data.frame()
  
  for (var_i in c("W1", "W2", "W3" ,"W4","W5", "W6","age_y", "sex","HCT", "MYCN","simpson_reciprocal", "group","CR")){
    print(var_i)
    formula_v <- as.formula(paste0("log10(c4_titer+1)~", var_i))
    df_i <- df_titer %>% filter(!is.na(.data[[var_i]]))
    fit_i <- lm(formula_v, data=df_i)
    res_i <- tidy(fit_i, conf.int = TRUE, conf.level = 0.95) %>% 
      filter(term != "(Intercept)") %>% 
      dplyr::rename(
        CI_low = conf.low,
        CI_high = conf.high
      ) %>% 
      mutate(
        variable = var_i,
        fold_change = 10^estimate,
        fold_change_CI_low = 10^CI_low,
        fold_change_CI_high = 10^CI_high,
        n = nrow(df_i)
      )
    uni_v_titer <- bind_rows(uni_v_titer, res_i)
  }
  
  write.csv(uni_v_titer, paste0("../Data/supplTable4_titer_CR",i,".csv"), row.names = F)
  
 # PFS
  cox_ui_res <- data.frame()
  for (var_i in c("age_y", "age_binary","MYCN","HCT","group", "sex","simpson_reciprocal", "W1","W2","W3","W4","W5","W6", "c4_high_median","c4_titer","CR")){
    df_i <- df_titer %>% filter(!is.na(.data[[var_i]]))

      formula_i <- as.formula(paste0("Surv(VPFS_upd, VRelapse) ~ ", var_i ) )
    fit_i <- coxph(formula_i, data = df_i)
    res_i <- tidy(fit_i, conf.int = TRUE, conf.level = 0.95) %>% 
      filter(term != "(Intercept)") %>% 
      mutate(
        variable = var_i,
        HR = exp(estimate),
        loer95 =  exp(estimate - 1.96 * std.error), 
        upper95  = exp(estimate + 1.96 * std.error),
        n = nrow(df_i)
      )
    cox_ui_res <- bind_rows(cox_ui_res, res_i)
  }
  write.csv(cox_ui_res, paste0("../../Data/supplTable5_PFS_CR",i,".csv"), row.names = F)
  
  
  # pcoa plot for CR1 and CR2
  # suppl Fig2b, suppl Fig2c
  ord <- phyloseq::ordinate(phyloseq3 %>%ps_filter(PriorRelapse==i) %>% tax_glom("genus"), method = "PCoA", distance = "bray")
  
  pcoa_df <- ord$vectors %>%
    data.frame() %>%
    dplyr::select(Axis.1, Axis.2) %>%
    rownames_to_column("sampleid") %>%
    left_join(
      data.frame(sample_data(phyloseq3 ))%>%
        rownames_to_column("sampleid") ,
      by = "sampleid"
    )
  a <- df_lda_docs %>% group_by(document) %>% dplyr::slice(which.max(gamma)) %>% ungroup() %>%
    mutate(topic=factor(topic))
  final_pcOA <- pcoa_df %>% left_join(a, by= c("sampleid"="document")) %>%filter(!is.na(gamma)) %>%
    ggplot(aes(x=Axis.1, y=Axis.2, color=topic)) +
    geom_point(size=2) + theme_bw() +
    scale_color_manual(values=color_vector,
                       name="Dominating\nmicrobial\nsignature") +
    ggtitle("")+
    xlab("")+
    ylab("")+
    theme(
      axis.text.x = element_text(size = 8, face="bold", angle= 0, vjust = 0.5),
      axis.text.y = element_text(size = 8, face="bold")
    )
  ggsave( paste0("../Figures/suppl_fig2_CR",i,"_pcoa.pdf"), final_pcOA, width = 4, height=3)
  
  
  
}



```

## KM plot
Fig 3a
```{r}
cr1_topic <- read.csv("../Data/09-CR1_df_topic.csv") %>% mutate(UPN=as.character(UPN)) %>%
  left_join(titers[,c("UPN","c4_titer","c4_high_median" )], by="UPN") %>%filter(!is.na(c4_titer)) %>%
  left_join(glucan[,c("UPN","time_glucan","group" )], by="UPN")%>%
  mutate(age_y = age_vaccine/12)%>%
  mutate(
    MYCN=factor(MYCN, levels=c("no","amplified")),
    HCT=factor(HCT, levels=c("no","yes")),
    PriorRelapse = factor(PriorRelapse, levels=c("1","2")),
    c4_high_median=factor(c4_high_median, levels = c("low_c4","high_c4")),
    VRelapse = as.numeric(VRelapse),
    age_binary = ifelse(age_y >=5,"older", "younger")
  )  

w2_df <- cr1_topic %>% mutate(
  w2_bin = ifelse(W2>= median(cr1_topic$W2), "High","Low")
)

fit_w2<-survfit(Surv(w2_df$VPFS_upd, w2_df$VRelapse)~w2_bin, data=w2_df)

p1 <- ggsurvplot(fit_w2, data=w2_df,
                 palette = c("#2166ac", "#b2182b"),
                 conf.int=TRUE,
                 pval=TRUE,
                 risk.table = T,
                 xlim = c(0,36), 
                 break.x.by = 6 )
ggsave("../Figures/Fig3a_CR1_W2_pfs_plot.pdf", p1$plot, height=4, width=5)
ggsave("../Figures/Fig3a_CR1_W2_pfs_table.pdf", p1$table, height=2, width=5)

```

* Suppl Fig2d
Erysipelatoclostridium signature distributation

```{r}
ggplot(cr1_topic, aes(x=W2))+
  geom_histogram(bins = 30, color = "black", fill = "steelblue") +
  theme_classic() +
  labs(
    x="Erysipelatoclostridium signature abundance",
    y="Number of Samples"
  )
ggsave("../Figures/Suppl_Fig2d_W2_distribution.pdf", width=3, height=3)
```

